[2023-09-04T14:06:02.439+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_with_python_dependencies_v03.get_sklearn scheduled__2023-02-08T00:00:00+00:00 [queued]>
[2023-09-04T14:06:02.473+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_with_python_dependencies_v03.get_sklearn scheduled__2023-02-08T00:00:00+00:00 [queued]>
[2023-09-04T14:06:02.474+0000] {taskinstance.py:1361} INFO - Starting attempt 5 of 6
[2023-09-04T14:06:02.535+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): get_sklearn> on 2023-02-08 00:00:00+00:00
[2023-09-04T14:06:02.563+0000] {standard_task_runner.py:57} INFO - Started process 7810 to run task
[2023-09-04T14:06:02.586+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dags_with_python_dependencies_v03', 'get_sklearn', 'scheduled__2023-02-08T00:00:00+00:00', '--job-id', '3608', '--raw', '--subdir', 'DAGS_FOLDER/dags_with_python_dependencies.py', '--cfg-path', '/tmp/tmp4_ww_apg']
[2023-09-04T14:06:02.600+0000] {standard_task_runner.py:85} INFO - Job 3608: Subtask get_sklearn
[2023-09-04T14:06:02.862+0000] {task_command.py:415} INFO - Running <TaskInstance: dags_with_python_dependencies_v03.get_sklearn scheduled__2023-02-08T00:00:00+00:00 [running]> on host 55ba52c92856
[2023-09-04T14:06:03.382+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mohghaff' AIRFLOW_CTX_DAG_ID='dags_with_python_dependencies_v03' AIRFLOW_CTX_TASK_ID='get_sklearn' AIRFLOW_CTX_EXECUTION_DATE='2023-02-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-02-08T00:00:00+00:00'
[2023-09-04T14:06:03.388+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags_with_python_dependencies.py", line 16, in get_sklearn
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2023-09-04T14:06:03.419+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dags_with_python_dependencies_v03, task_id=get_sklearn, execution_date=20230208T000000, start_date=20230904T140602, end_date=20230904T140603
[2023-09-04T14:06:03.476+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3608 for task get_sklearn (No module named 'sklearn'; 7810)
[2023-09-04T14:06:03.531+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-04T14:06:03.595+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
